export default function Props3(){
    const tableTitle=[
        {name:'ID'},
        {name:'Name'},
        {name:'Age'},
        {name:'Course'},
        {name:'Grade'}
    ]
    const tableDetails=[
    [
        {id:'1'},
        {id:'2'},
        {id:'3'},
        {id:'4'},
        {id:'5'},
        {id:'6'},
        {id:'7'}
    ],
    [
        {name:'Maya'},
        {name:'Arun'},
        {name:'Meena'},
        {name:'Ravi'},
        {name:'Priya'},
        {name:'Karthik'},
        {name:'Ananya'}
    ],
    [
        {age:'21'},
        {age:'22'},
        {age:'20'},
        {age:'23'},
        {age:'21'},
        {age:'22'},
        {age:'20'}
    ],
    [
        {course:'React'},
        {course:'JavaScript'},
        {course:'HTML & CSS'},
        {course:'Node.js'},
        {course:'Python'},
        {course:'Java'},
        {course:'CSS & Bootstrap'}
    ],
    [
        {grade:'A'},
        {grade:'B'},
        {grade:'A'},
        {grade:'B+'},
        {grade:'A-'},
        {grade:'B'},
        {grade:'A'},
    ]
]
    return(
        <>
        <table border='1' style={{border:'1px solid black',fontSize:'30px',borderCollapse:'collapse'}}>
            <tr>
                <th>{tableTitle[0].name}</th>
                <th>{tableTitle[1].name}</th>
                <th>{tableTitle[2].name}</th>
                <th>{tableTitle[3].name}</th>
                <th>{tableTitle[4].name}</th>
            </tr>
            <tr>
                <td>{tableDetails[0][0].id}</td>
                <td>{tableDetails[1][0].name}</td>
                <td>{tableDetails[2][0].age}</td>
                <td>{tableDetails[3][0].course}</td>
                <td>{tableDetails[4][0].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][1].id}</td>
                <td>{tableDetails[1][1].name}</td>
                <td>{tableDetails[2][1].age}</td>
                <td>{tableDetails[3][1].course}</td>
                <td>{tableDetails[4][1].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][2].id}</td>
                <td>{tableDetails[1][2].name}</td>
                <td>{tableDetails[2][2].age}</td>
                <td>{tableDetails[3][2].course}</td>
                <td>{tableDetails[4][2].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][3].id}</td>
                <td>{tableDetails[1][3].name}</td>
                <td>{tableDetails[2][3].age}</td>
                <td>{tableDetails[3][3].course}</td>
                <td>{tableDetails[4][3].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][4].id}</td>
                <td>{tableDetails[1][4].name}</td>
                <td>{tableDetails[2][4].age}</td>
                <td>{tableDetails[3][4].course}</td>
                <td>{tableDetails[4][4].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][5].id}</td>
                <td>{tableDetails[1][5].name}</td>
                <td>{tableDetails[2][5].age}</td>
                <td>{tableDetails[3][5].course}</td>
                <td>{tableDetails[4][5].grade}</td>
            </tr>
            <tr>
                <td>{tableDetails[0][6].id}</td>
                <td>{tableDetails[1][6].name}</td>
                <td>{tableDetails[2][6].age}</td>
                <td>{tableDetails[3][6].course}</td>
                <td>{tableDetails[4][6].grade}</td>
            </tr>
        </table>
        </>
    )
}